// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneriqueCRUD.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GeneriqueCRUD.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hammer",
                            Price = 12
                        },
                        new
                        {
                            Id = 2,
                            Name = "Screwdriver",
                            Price = 8
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wrench",
                            Price = 15
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pliers",
                            Price = 7
                        },
                        new
                        {
                            Id = 5,
                            Name = "Saw",
                            Price = 22
                        },
                        new
                        {
                            Id = 6,
                            Name = "Drill",
                            Price = 45
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tape Measure",
                            Price = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "Level",
                            Price = 9
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chisel",
                            Price = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "Allen Wrench Set",
                            Price = 12
                        });
                });

            modelBuilder.Entity("GeneriqueCRUD.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
