// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filtre.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Filtre.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "Outils de Bureau",
                            Cout = 705.56699541469m,
                            Nom = "Produit1"
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Outils de Jardin",
                            Cout = 205.100952164347m,
                            Nom = "Produit2"
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Outils de Bureau",
                            Cout = 206.520016288287m,
                            Nom = "Produit3"
                        },
                        new
                        {
                            Id = 4,
                            Categorie = "Outils de Cuisine",
                            Cout = 588.071161974821m,
                            Nom = "Produit4"
                        },
                        new
                        {
                            Id = 5,
                            Categorie = "Outils de Cuisine",
                            Cout = 280.450317584915m,
                            Nom = "Produit5"
                        },
                        new
                        {
                            Id = 6,
                            Categorie = "Outils de Construction",
                            Cout = 15.9243383287001m,
                            Nom = "Produit6"
                        },
                        new
                        {
                            Id = 7,
                            Categorie = "Outils Électroniques",
                            Cout = 392.906242148192m,
                            Nom = "Produit7"
                        },
                        new
                        {
                            Id = 8,
                            Categorie = "Outils de Bureau",
                            Cout = 687.429973987551m,
                            Nom = "Produit8"
                        },
                        new
                        {
                            Id = 9,
                            Categorie = "Outils de Bureau",
                            Cout = 255.779996475871m,
                            Nom = "Produit9"
                        },
                        new
                        {
                            Id = 10,
                            Categorie = "Outils de Cuisine",
                            Cout = 527.727348369815m,
                            Nom = "Produit10"
                        },
                        new
                        {
                            Id = 11,
                            Categorie = "Outils Électroniques",
                            Cout = 740.028947672801m,
                            Nom = "Produit11"
                        },
                        new
                        {
                            Id = 12,
                            Categorie = "Outils de Bureau",
                            Cout = 577.045086090831m,
                            Nom = "Produit12"
                        },
                        new
                        {
                            Id = 13,
                            Categorie = "Outils de Bureau",
                            Cout = 575.514482892407m,
                            Nom = "Produit13"
                        },
                        new
                        {
                            Id = 14,
                            Categorie = "Outils de Bureau",
                            Cout = 591.31666940571m,
                            Nom = "Produit14"
                        },
                        new
                        {
                            Id = 15,
                            Categorie = "Outils de Cuisine",
                            Cout = 454.380084315283m,
                            Nom = "Produit15"
                        },
                        new
                        {
                            Id = 16,
                            Categorie = "Outils Électroniques",
                            Cout = 500.678584022162m,
                            Nom = "Produit16"
                        },
                        new
                        {
                            Id = 17,
                            Categorie = "Outils Électroniques",
                            Cout = 250.8492565562m,
                            Nom = "Produit17"
                        },
                        new
                        {
                            Id = 18,
                            Categorie = "Outils de Jardin",
                            Cout = 285.845113980063m,
                            Nom = "Produit18"
                        },
                        new
                        {
                            Id = 19,
                            Categorie = "Outils Électroniques",
                            Cout = 765.707879989936m,
                            Nom = "Produit19"
                        },
                        new
                        {
                            Id = 20,
                            Categorie = "Outils de Bureau",
                            Cout = 613.996225096506m,
                            Nom = "Produit20"
                        },
                        new
                        {
                            Id = 21,
                            Categorie = "Outils de Bureau",
                            Cout = 913.708009184157m,
                            Nom = "Produit21"
                        },
                        new
                        {
                            Id = 22,
                            Categorie = "Outils Électroniques",
                            Cout = 994.575586954089m,
                            Nom = "Produit22"
                        },
                        new
                        {
                            Id = 23,
                            Categorie = "Outils de Construction",
                            Cout = 623.835665524928m,
                            Nom = "Produit23"
                        },
                        new
                        {
                            Id = 24,
                            Categorie = "Outils de Construction",
                            Cout = 724.81820721172m,
                            Nom = "Produit24"
                        },
                        new
                        {
                            Id = 25,
                            Categorie = "Outils de Construction",
                            Cout = 14.4342123921906m,
                            Nom = "Produit25"
                        },
                        new
                        {
                            Id = 26,
                            Categorie = "Outils de Bureau",
                            Cout = 709.566820810732m,
                            Nom = "Produit26"
                        },
                        new
                        {
                            Id = 27,
                            Categorie = "Outils de Construction",
                            Cout = 87.2406831277236m,
                            Nom = "Produit27"
                        },
                        new
                        {
                            Id = 28,
                            Categorie = "Outils Électroniques",
                            Cout = 578.034678789432m,
                            Nom = "Produit28"
                        },
                        new
                        {
                            Id = 29,
                            Categorie = "Outils de Bureau",
                            Cout = 416.327541467702m,
                            Nom = "Produit29"
                        },
                        new
                        {
                            Id = 30,
                            Categorie = "Outils de Construction",
                            Cout = 727.735815188154m,
                            Nom = "Produit30"
                        },
                        new
                        {
                            Id = 31,
                            Categorie = "Outils Électroniques",
                            Cout = 30.8173510185216m,
                            Nom = "Produit31"
                        },
                        new
                        {
                            Id = 32,
                            Categorie = "Outils Électroniques",
                            Cout = 649.672729859451m,
                            Nom = "Produit32"
                        },
                        new
                        {
                            Id = 33,
                            Categorie = "Outils de Bureau",
                            Cout = 61.4927058273642m,
                            Nom = "Produit33"
                        },
                        new
                        {
                            Id = 34,
                            Categorie = "Outils de Construction",
                            Cout = 961.990867710898m,
                            Nom = "Produit34"
                        },
                        new
                        {
                            Id = 35,
                            Categorie = "Outils Électroniques",
                            Cout = 12.5256704614207m,
                            Nom = "Produit35"
                        },
                        new
                        {
                            Id = 36,
                            Categorie = "Outils de Bureau",
                            Cout = 800.40531426256m,
                            Nom = "Produit36"
                        },
                        new
                        {
                            Id = 37,
                            Categorie = "Outils de Construction",
                            Cout = 813.212996925921m,
                            Nom = "Produit37"
                        },
                        new
                        {
                            Id = 38,
                            Categorie = "Outils de Bureau",
                            Cout = 749.359517368722m,
                            Nom = "Produit38"
                        },
                        new
                        {
                            Id = 39,
                            Categorie = "Outils de Bureau",
                            Cout = 607.810458938784m,
                            Nom = "Produit39"
                        },
                        new
                        {
                            Id = 40,
                            Categorie = "Outils de Cuisine",
                            Cout = 792.524020508284m,
                            Nom = "Produit40"
                        },
                        new
                        {
                            Id = 41,
                            Categorie = "Outils de Bureau",
                            Cout = 290.90193809216m,
                            Nom = "Produit41"
                        },
                        new
                        {
                            Id = 42,
                            Categorie = "Outils Électroniques",
                            Cout = 841.97791475142m,
                            Nom = "Produit42"
                        },
                        new
                        {
                            Id = 43,
                            Categorie = "Outils Électroniques",
                            Cout = 613.877867317218m,
                            Nom = "Produit43"
                        },
                        new
                        {
                            Id = 44,
                            Categorie = "Outils Électroniques",
                            Cout = 641.277676328149m,
                            Nom = "Produit44"
                        },
                        new
                        {
                            Id = 45,
                            Categorie = "Outils de Bureau",
                            Cout = 271.675399489621m,
                            Nom = "Produit45"
                        },
                        new
                        {
                            Id = 46,
                            Categorie = "Outils de Cuisine",
                            Cout = 461.279509603834m,
                            Nom = "Produit46"
                        },
                        new
                        {
                            Id = 47,
                            Categorie = "Outils de Jardin",
                            Cout = 445.947469937594m,
                            Nom = "Produit47"
                        },
                        new
                        {
                            Id = 48,
                            Categorie = "Outils de Cuisine",
                            Cout = 512.972882156412m,
                            Nom = "Produit48"
                        },
                        new
                        {
                            Id = 49,
                            Categorie = "Outils Électroniques",
                            Cout = 65.1867425422865m,
                            Nom = "Produit49"
                        },
                        new
                        {
                            Id = 50,
                            Categorie = "Outils Électroniques",
                            Cout = 460.29262242973m,
                            Nom = "Produit50"
                        },
                        new
                        {
                            Id = 51,
                            Categorie = "Outils de Jardin",
                            Cout = 363.675986057048m,
                            Nom = "Produit51"
                        },
                        new
                        {
                            Id = 52,
                            Categorie = "Outils de Jardin",
                            Cout = 23.4858382992387m,
                            Nom = "Produit52"
                        },
                        new
                        {
                            Id = 53,
                            Categorie = "Outils Électroniques",
                            Cout = 928.498345811805m,
                            Nom = "Produit53"
                        },
                        new
                        {
                            Id = 54,
                            Categorie = "Outils de Cuisine",
                            Cout = 43.7762721932401m,
                            Nom = "Produit54"
                        },
                        new
                        {
                            Id = 55,
                            Categorie = "Outils Électroniques",
                            Cout = 924.19060990014m,
                            Nom = "Produit55"
                        },
                        new
                        {
                            Id = 56,
                            Categorie = "Outils de Cuisine",
                            Cout = 536.89064373376m,
                            Nom = "Produit56"
                        },
                        new
                        {
                            Id = 57,
                            Categorie = "Outils de Cuisine",
                            Cout = 725.497648325722m,
                            Nom = "Produit57"
                        },
                        new
                        {
                            Id = 58,
                            Categorie = "Outils de Cuisine",
                            Cout = 743.618909674994m,
                            Nom = "Produit58"
                        },
                        new
                        {
                            Id = 59,
                            Categorie = "Outils de Jardin",
                            Cout = 392.254958749378m,
                            Nom = "Produit59"
                        },
                        new
                        {
                            Id = 60,
                            Categorie = "Outils de Construction",
                            Cout = 516.168568816513m,
                            Nom = "Produit60"
                        },
                        new
                        {
                            Id = 61,
                            Categorie = "Outils Électroniques",
                            Cout = 327.318159684681m,
                            Nom = "Produit61"
                        },
                        new
                        {
                            Id = 62,
                            Categorie = "Outils de Cuisine",
                            Cout = 403.740355932213m,
                            Nom = "Produit62"
                        },
                        new
                        {
                            Id = 63,
                            Categorie = "Outils de Construction",
                            Cout = 913.389838494063m,
                            Nom = "Produit63"
                        },
                        new
                        {
                            Id = 64,
                            Categorie = "Outils Électroniques",
                            Cout = 882.226561482223m,
                            Nom = "Produit64"
                        },
                        new
                        {
                            Id = 65,
                            Categorie = "Outils Électroniques",
                            Cout = 974.695765296579m,
                            Nom = "Produit65"
                        },
                        new
                        {
                            Id = 66,
                            Categorie = "Outils de Bureau",
                            Cout = 848.938516810375m,
                            Nom = "Produit66"
                        },
                        new
                        {
                            Id = 67,
                            Categorie = "Outils de Bureau",
                            Cout = 85.3691200686986m,
                            Nom = "Produit67"
                        },
                        new
                        {
                            Id = 68,
                            Categorie = "Outils de Jardin",
                            Cout = 316.149773708641m,
                            Nom = "Produit68"
                        },
                        new
                        {
                            Id = 69,
                            Categorie = "Outils Électroniques",
                            Cout = 586.365199944543m,
                            Nom = "Produit69"
                        },
                        new
                        {
                            Id = 70,
                            Categorie = "Outils de Cuisine",
                            Cout = 283.798142264672m,
                            Nom = "Produit70"
                        },
                        new
                        {
                            Id = 71,
                            Categorie = "Outils de Jardin",
                            Cout = 654.156118295999m,
                            Nom = "Produit71"
                        },
                        new
                        {
                            Id = 72,
                            Categorie = "Outils de Bureau",
                            Cout = 312.773502524768m,
                            Nom = "Produit72"
                        },
                        new
                        {
                            Id = 73,
                            Categorie = "Outils de Cuisine",
                            Cout = 269.706004026048m,
                            Nom = "Produit73"
                        },
                        new
                        {
                            Id = 74,
                            Categorie = "Outils de Cuisine",
                            Cout = 763.54156867921m,
                            Nom = "Produit74"
                        },
                        new
                        {
                            Id = 75,
                            Categorie = "Outils de Bureau",
                            Cout = 328.366043835136m,
                            Nom = "Produit75"
                        },
                        new
                        {
                            Id = 76,
                            Categorie = "Outils de Bureau",
                            Cout = 686.50366557886m,
                            Nom = "Produit76"
                        },
                        new
                        {
                            Id = 77,
                            Categorie = "Outils de Bureau",
                            Cout = 298.615715395412m,
                            Nom = "Produit77"
                        },
                        new
                        {
                            Id = 78,
                            Categorie = "Outils de Construction",
                            Cout = 282.216137894946m,
                            Nom = "Produit78"
                        },
                        new
                        {
                            Id = 79,
                            Categorie = "Outils de Jardin",
                            Cout = 145.99891194452m,
                            Nom = "Produit79"
                        },
                        new
                        {
                            Id = 80,
                            Categorie = "Outils de Bureau",
                            Cout = 602.83638558436m,
                            Nom = "Produit80"
                        },
                        new
                        {
                            Id = 81,
                            Categorie = "Outils de Bureau",
                            Cout = 811.480433094934m,
                            Nom = "Produit81"
                        },
                        new
                        {
                            Id = 82,
                            Categorie = "Outils Électroniques",
                            Cout = 950.565313729813m,
                            Nom = "Produit82"
                        },
                        new
                        {
                            Id = 83,
                            Categorie = "Outils de Bureau",
                            Cout = 794.63873019848m,
                            Nom = "Produit83"
                        },
                        new
                        {
                            Id = 84,
                            Categorie = "Outils de Bureau",
                            Cout = 129.914363484727m,
                            Nom = "Produit84"
                        },
                        new
                        {
                            Id = 85,
                            Categorie = "Outils Électroniques",
                            Cout = 55.1769831079741m,
                            Nom = "Produit85"
                        },
                        new
                        {
                            Id = 86,
                            Categorie = "Outils de Construction",
                            Cout = 475.41834151161m,
                            Nom = "Produit86"
                        },
                        new
                        {
                            Id = 87,
                            Categorie = "Outils de Jardin",
                            Cout = 613.211863272184m,
                            Nom = "Produit87"
                        },
                        new
                        {
                            Id = 88,
                            Categorie = "Outils de Construction",
                            Cout = 701.592612715425m,
                            Nom = "Produit88"
                        },
                        new
                        {
                            Id = 89,
                            Categorie = "Outils de Construction",
                            Cout = 535.010671993226m,
                            Nom = "Produit89"
                        },
                        new
                        {
                            Id = 90,
                            Categorie = "Outils Électroniques",
                            Cout = 796.605680708892m,
                            Nom = "Produit90"
                        },
                        new
                        {
                            Id = 91,
                            Categorie = "Outils de Bureau",
                            Cout = 758.102002920099m,
                            Nom = "Produit91"
                        },
                        new
                        {
                            Id = 92,
                            Categorie = "Outils Électroniques",
                            Cout = 56.9281756123298m,
                            Nom = "Produit92"
                        },
                        new
                        {
                            Id = 93,
                            Categorie = "Outils de Cuisine",
                            Cout = 992.327517579421m,
                            Nom = "Produit93"
                        },
                        new
                        {
                            Id = 94,
                            Categorie = "Outils de Cuisine",
                            Cout = 715.63885409924m,
                            Nom = "Produit94"
                        },
                        new
                        {
                            Id = 95,
                            Categorie = "Outils de Construction",
                            Cout = 401.758375935812m,
                            Nom = "Produit95"
                        },
                        new
                        {
                            Id = 96,
                            Categorie = "Outils de Bureau",
                            Cout = 89.7491597003674m,
                            Nom = "Produit96"
                        },
                        new
                        {
                            Id = 97,
                            Categorie = "Outils de Cuisine",
                            Cout = 214.620418708293m,
                            Nom = "Produit97"
                        },
                        new
                        {
                            Id = 98,
                            Categorie = "Outils de Construction",
                            Cout = 854.717016320794m,
                            Nom = "Produit98"
                        },
                        new
                        {
                            Id = 99,
                            Categorie = "Outils Électroniques",
                            Cout = 585.725173308487m,
                            Nom = "Produit99"
                        },
                        new
                        {
                            Id = 100,
                            Categorie = "Outils de Construction",
                            Cout = 140.432921751813m,
                            Nom = "Produit100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
